name: Build and Schedule Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Restore dependencies
        run: dotnet restore github4women/github4women.csproj
      
      - name: Build Project
        run: dotnet build github4women/github4women.csproj --configuration Release

      - name: Show current directory
        run: pwd

      - name: List files in github4women directory
        run: ls -la github4women/

      - name: Show content of Index.cshtml
        run: cat github4women/Pages/Index.cshtml

